MVCSistemaWebTransportes/Models/Auto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MVCSistemaWebTransportes.Validations;

namespace MVCSistemaWebTransportes.Models
{
    public class Auto
    {
        public int Id { get; set; }
        [Required]
        public string Modelo { get; set; }
        [Required]
        public string Marca { get; set; }
        [Required]
        [CheckValidYear]
        public int Año { get; set; }
        [Required]
        public string Color { get; set; }

    }
}

MVCSistemaWebTransportes/Controllers/AutoController.cs
using MVCSistemaWebTransportes.Data;
using MVCSistemaWebTransportes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCSistemaWebTransportes.Controllers
{
    public class AutoController : Controller
    {
        private AutoDBContext context = new AutoDBContext();
        public AutoController() { this.context = context; }


        // GET: Auto/Index
        public ActionResult Index()
        {
            return View("Index", context.Autos.ToList());
        }

        //GET Auto/Create

        [HttpGet]
        public ActionResult Create()
        {
            Auto auto = new Auto();
            return View("Create",auto);
        }

        [HttpPost]
        public ActionResult Create(Auto auto)
        {
            if(ModelState.IsValid)
            {
                context.Autos.Add(auto);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View("Create", auto);
            }
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            Auto auto = context.Autos.Find(id);
            if(auto == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View("Details", auto);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Auto auto = context.Autos.Find(id);
            if(auto == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View("Delete", auto);
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Auto auto = context.Autos.Find(id);
            if(auto !=null)
            {
                context.Autos.Remove(auto); 
                context.SaveChanges();             
            }
            return RedirectToAction("Index");
        }

    }
}

MVCSistemaWebTransportes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCSistemaWebTransportes.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Fecha = DateTime.Now.ToString();
            ViewBag.Message = "Bienvenido al Sitio Web";
            return View();
        }

    }
}

MVCSistemaWebTransportes/Views/Auto/Create.cshtml
@model MVCSistemaWebTransportes.Models.Auto

@{
    ViewBag.Title = "Create";
}

<h1>Nuevo Auto</h1>
@using (Html.BeginForm("Create", "Auto", FormMethod.Post))
{
<p>
    @Html.LabelFor(model => model.Marca)
    @Html.EditorFor(model => model.Marca)
    @Html.ValidationMessageFor(model => model.Marca)
</p>

<p>
    @Html.LabelFor(model => model.Modelo)
    @Html.EditorFor(model => model.Modelo)
    @Html.ValidationMessageFor(model => model.Modelo)
</p>

<p>
    @Html.LabelFor(model => model.Año)
    @Html.EditorFor(model => model.Año)
    @Html.ValidationMessageFor(model => model.Año)
</p>
<p>
    @Html.LabelFor(model => model.Color)
    @Html.EditorFor(model => model.Color)
    @Html.ValidationMessageFor(model => model.Color)
</p>
<input type="submit" value="Crear" />

@Html.ActionLink("Volver al Indice", "Index", "Auto")
}

MVCSistemaWebTransportes/Views/Auto/Delete.cshtml
@model MVCSistemaWebTransportes.Models.Auto

@{
    ViewBag.Title = "Delete";
}

<h2>Auto</h2>
<p>Desea eliminar este Auto?</p>

@using (Html.BeginForm("Delete", "Auto", FormMethod.Post))
{
<div>
    <span>@Html.DisplayNameFor(model => model.Marca)</span>
    <span>@Html.DisplayFor(model => model.Marca)</span>
    <span>@Html.DisplayNameFor(model => model.Modelo)</span>
    <span>@Html.DisplayFor(model => model.Modelo)</span>
    <span>@Html.DisplayNameFor(model => model.Año)</span>
    <span>@Html.DisplayFor(model => model.Año)</span>
</div>
<input type="submit" value="Eliminar" />
}

<p>
    @Html.ActionLink("Volver al Index", "Index", "Auto")
</p>

MVCSistemaWebTransportes/Views/Auto/Details.cshtml
@model MVCSistemaWebTransportes.Models.Auto

@{
    ViewBag.Title = "Details";
}

<fieldset>
    <legend>Auto Detalle</legend>
    <div>
        @Html.DisplayNameFor(model => model.Marca)
    </div>
    <div>
        @Html.DisplayFor(model => model.Marca)
    </div>
    <div>
        @Html.DisplayNameFor(model => model.Modelo)
    </div>
    <div>
        @Html.DisplayFor(model => model.Modelo)
    </div>
    <div>
        @Html.DisplayNameFor(model => model.Año)
    </div>
    <div>
        @Html.DisplayFor(model => model.Año)
    </div>
    <div>
        @Html.DisplayNameFor(model => model.Color)
    </div>
    <div>
        @Html.DisplayFor(model => model.Color)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Volver al Index", "Index", "Auto")
</p>

MVCSistemaWebTransportes/Views/Auto/Index.cshtml
@model IEnumerable<MVCSistemaWebTransportes.Models.Auto>
@{
    ViewBag.Title = "Index";
}

<div>
    <p>
        @Html.ActionLink("Crear", "Create")
    </p>
    <table>
        <tr>
            <th>@Html.DisplayNameFor(model=>model.Modelo)</th>
            <th>@Html.DisplayNameFor(model => model.Marca)</th>
            <th>@Html.DisplayNameFor(model => model.Año)</th>
            <th>@Html.DisplayNameFor(model => model.Color)</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem=>item.Modelo)</td>
                <td>@Html.DisplayFor(modelItem => item.Marca)</td>
                <td>@Html.DisplayFor(modelItem => item.Año)</td>
                <td>@Html.DisplayFor(modelItem => item.Color)</td>
                <td>@Html.ActionLink("Detalle","Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("Eliminar", "Delete", new { id = item.Id })</td>
            </tr>
        }

    </table>
</div>

MVCSistemaWebTransportes/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div>
    <h3>@ViewBag.Fecha</h3>
    <h4>@ViewBag.Message</h4>
</div>

MVCSistemaWebTransportes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body>
    <div class="myHeader">
        <div id="headerContent">
            <h1>Header content</h1>
        </div>
        <div id="ads">
            <p>Ads content</p>
        </div>
    </div>
    <div id="section">
        <div id="navBar">
            @if (IsSectionDefined("navBar"))
            {
                @RenderSection("navBar")
            }
            else
            {
                <p>Zona Nav</p>

            }


        </div>
        <div id="artFoot">
            <div id="article">
                @RenderBody()

            </div>
            <div id="footer">
                <h3>Footer</h3>
            </div>
        </div>
    </div>
    
</body>
</html>